# -*- coding: utf-8 -*-
"""ro706class1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eYyUIcJ55bRRKESAFDZhAWKXGpWzcU47
"""

# day 1 python class
a = "RoHit" # value of 'a' is aditya
s,b,c=1,2,"rohit" #value of 's','b','c' is 1,2,"rohit"
a
print(a) #printing value 'a'
print(type(a))#printing value datatype
print(len(a))#printing lengthof the variable 'a'
print(id(a))#printing id or you can say that printing storage location of varial 'a'
print(a.upper())#printing  variable 'a' upper value
print(a.lower())#printing variable 'a' lower value
print()
list1=list(input("enter value:"))
print(list1)
print(len(list1))
for i in list1:
    print(i)
print(s,b,c)#printing multiple values
print(isinstance(a,int))
print(isinstance(b,int))
a = "rohit"
n = len(a)
print(n)

#day 2 python class
x = str(3)
print(type(x))
y = int(3)
print(type(y))
y = float(3)
print(x)
print(y)
print(type(y))
c =0b100 #for binary number system
print(type(c))
print(c)
print(int("300",5))
print(int("1010",2))
print(int("12120",3))
print(int("1111111",2))
print(int("66226",7))
print(int("6622611",32))
a = 0b1010 #binary
b = 0o170 #octal
print(a,b)
h = 2+3.14j #complex literal
print(h)
print(complex(3+84))
print (u'\u00dc \n nic\n')
print('Omega: \u03A9')
name = "rohit"
classes = "12/G"
adress="sec -4 G qno-241"
print(name,classes,adress)

#my work
num= int(input("enter any four digit number:"))
sum=0
for i in str(num):
    sum += int(i)
print (sum)

#day 3 python class
print(ord("h"))
print(chr(122))
print(int(0x00dc))
print(int(0x012dc))
a = True
b = False
print(a + 100, b+100)
str_my = "sparshm"
print(str_my [1])
print(str_my[-1])
print(str_my[1:4])
print(str_my[0:5:2])
print(str_my[5:0:-1])
print(str_my[::2])

#write a program to declare a string consisting  of all digits from 0-9 print all,odd,and even digits from the string
my_str = "0123456789"
print(my_str)
print(my_str[::2])#even
print(my_str[1:10:2])#odd
m_s = "sitnagpur"
print(m_s[-3:-5:-1])
print(m_s[5:2:-1])
#write a program to add two number
a = 3
b = 4
c = a+b
print(c)
#write a program to  input form user
username = str(input("please enter your name:"))
print("hello ",username)

#day 4 python class
my_str="rohit mandal"
s1 = my_str.split()
s2 = my_str.split(sep = " ")
print(s1,s2)
my_str = "rohitmandal"
s1 = my_str.split(sep = "a")
print(s1)
name = input("enter your name: ")
print("hello",name)
print(type(name))
name = input("enter your name:")
print("Hello",name.upper())
print("hello ",name.title())
y,x= input("enter two naumber: ").split()
print(int(x)+int(y))
#real number and perform it multplication
real1 = float(input("enter your real number1: "))
real2 = float(input("enter your real number2: "))
print(real1*real2)
#wap to get your name as input and print ascii value 
name = input("enter your name: ")
a = len(name)
print("name len =", a)
for i in range(int(a)):
    print(ord(name[i]))
print("thank you")

name = input("enter your name: ")
a = len(name)
print("name len =", a)
for i in range(int(a)):
    print(ord(name[i]))
print("thank you")

ro706 = "hello rohit"
num = 100
text = "%s your marks: %d"%(ro706,num)
print(text)
morpheus7104 = "chutiya"
yu = 111
xxx = "%s is not : %d"%(morpheus7104,yu)
print(xxx)

#home work
str_my = input("enter your name:")
print(str_my.isalpha())
print(str_my[0].isalpha())
print(str_my.isdigit())#1
print(str_my.isidentifier())#2
print(str_my.islower())#3
print(str_my.title().istitle())#4
print(str_my.istitle())#5
table = {110:97,122:98,117:None}
print(str_my.translate(table))#6
print(str_my.swapcase())#7
print(str_my.casefold())#8
print(str_my.capitalize())#9
print(str_my.endswith("mandal"))#10
print(str_my.startswith("rohit"))#11
print(str_my.zfill(7))#12
list1 =[1,2,3,4]
print(list1.index(2))#13
print(str_my.find("k"))#14
print(str_my.count("rohit"))#15
print(str_my.rfind("o"))#16
print(str_my.encode())#17
print(str_my.center(23))#18
print(str_my.center(20))#19
print(str_my.isdecimal())#20
print(str_my.isnumeric())#21

#list 
list1 =list(input("enter your letter list:"))
print(list1)
print(list1[1])
n = 0
for i in list1:
    print(list1[n])
    n +=1

for i in range(00,100,2):
    print(i)
    if i  == 28:
      print("nice")
      break
    else:
      pass

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
print(months[6],"\n")
print(months[6:9],"\n")
print(months[0:11:2],"\n")
print(months[-12:-1])
print(months[-12:-1])
print(months[12:1:-1])
print(months[12:5:-1])
print(months[12:3:-1])
print(months[-1:-5:-1])
print(months[-12:-8:1],"\n")
list1=list(range(-4,10,2))
print("list1=",list1)
list2 =list(range(-6,6,1))
print("list2",list2)
print(list1+list2)
print(list2 * 2)
print(list1 in list2)
print(list1 not in list2 )
n = 0
list1.append(1)
print(list1)
list1.insert(0,11) #insert(indexnumber,element name or number)
print("list1 =",list1)
l=list1.sort()
print(sorted(list1,reverse=True))

#to find the sum of 5 digit number
a = []
a.append(int(input("enter number 1:")))
a.append(int(input("enter number 2:")))
a.append(int(input("enter number 3:")))
a.append(int(input("enter number 4:")))
a.append(int(input("enter number 5:")))
sum = a[0]+a[1]+a[2]+a[3]+a[4]
print("sum=",sum)

#1)to find the sum of 5 digit number
#2)to find weather arm is or not
#1)
a = b = int(input("enter any 5 digit number:"))
b = a%10
a = a//10
b1 = a%10
a = a//10
b2 = a%10
a = a//10
b3 = a%10
a = a//10
b4 = a%10
a =  a//10
print(b,b1,b2,b3,b4)
print('sum',b+b1+b2+b3+b4)

a = b = int(input("enter any 3 digit number:"))
b = a%10
a = a//10
b1 = a%10
a = a//10
b2 = a%10
print(b**3+b1**3+b2**3)
print('armstrong number')

num = int(input("enter number:"))
ans = 0
digits = len(str(num))
dup_number = num
while (dup_number != 0):
    remainder = dup_number % 10
    ans = ans + remainder**digits
    dup_number = dup_number//10
if(num == ans):
    print(num, "is Armstrong number")
else:
    print(num, "is not Armstrong number")

#day 6 python class
list1= ["CAT","DOG","TIGER","JAK","apple"]
print(sorted(list1,key=str.lower))
list1 =[[1,2,3,4],["rohit","riya","raj","khushi"],[36,37,32,33]]
print(list1)
print("list1 =",list1[0],"list2=",list1[1],"list3=",list1[2])
print(list1[0:3][0:3])
#tuple
t =(1,2,3,4,"three")
print(t)
print(type(t))
t = (1,2,3,4,5)
a,b,c,d,e = t
print(a,b,c,d)
for i in t:
    print(i)
del t
print("tuple is deleted successfully")
t = ("21-06-2004",["rohit","sager"])
r = ("21-06-2004",["rohit","sager"])
print(r == t)
print(id(r),id(t))
print(t is r)
t = r
print(r == t)
print(id(r),id(t))
print(t is r)
list1 = t[1]
list1.append("ro706")
print(t)
'''t[1]=[1,2,3]
print(t)'''
set1 = {1,2,3,4}
print(set1) 
set1.add(0)
set1.update([10,11,12,13])
print(set1)
set1.pop()
#set1.clear()
print(set1)
set1.remove(10)
print(set1)
set1.discard(0)
set2 = {1,2,3,0,10}
print(set2)

set1 = {1,2,3,4}
a= (1.0,(1,2,3),"hello")
set2=a
print(set1)
print(set2)

t1 = ()
t2 = (1,2,3)
t3 = (1,"hello",34)
print(t1)
print(t2)
print(t3)

t1 = (3,46,"cat")
print(t1)
print(t1[0])
print(t1[1])
print(t1[2])

tuple1 = (0,1,2,3)
tuple2 = ("SIT","Nagpur")
tuple3 = tuple1 + tuple2
print("tuple1 \n",tuple1) 
print("tuple2 \n",tuple2)
print("tuple after concetnation \n",tuple3)

classroll = {"rohit":7,"aditya":24,"nishant":61,"anmol":23,"devanshu":22}
print(classroll)
classroll['rohit']=75
classroll['aditya'] = 92
classroll["nishant"]=125
classroll['anmol'] = 91
classroll['devanshu'] = 90
print(classroll)
print(classroll.keys())
print(classroll.values())
print(type(classroll))
print(1,2,3,4)
print(1,2,3,4, sep ="#" ,end="$")
print(1,2,3,4, sep =' ',end ="\n")
print(1,2,3,4, sep ="@",end="$",flush = True)
print("")
print("     *","    * *","   * * *","  * * * *",sep ="\n",end ="")

#python class 8
x = 23
y = 82
print("two value are {1} and {0}".format(x,y))
print(f"two value are {x} and {y}")
''' 
arithmatic oprators : +,-,/,*,%,//,**[BODMAS]
comparison oprators : <,>,==,,!=,>=,<=
logical oprators : and ,or,not
bitwise oprator : !,&,~,^,>>,<<
'''
print(5<<3)
print(10 >> 2)
print(5&6)
letter = input('enter character:')
print('vowel') if letter in 'aeiou'else print('no vowel')

#wap to check weather enter number is even or odd by using bitwise
num = int(input("enter num:"))
print('odd') if num&1== 1 else print("even")
#wap to fine the largest of two number

num1 = int(input("enter num1:"))
num2 =int(input("enter num2"))
print("num1 is greater than num2") if num1 > num2 else print("num2 is graeter than num2")

num1 = int(input("enter num1:"))
num2 =int(input("enter num2:"))
num3 = int(input("enter num3:"))
a = 0
print("num1") if num1 > num2 or num1 > num3 else print("num3")

num1 = int(input("enter num1:"))
num2 =int(input("enter num2:"))
num3 = int(input("enter num3:"))
a = num1 if num1 > num2 else num2
a = a if a > num3 else num3
print(a)

#wap to create list of 3 friend.check if amit is present in the list or not if amit is not in the list append/add amit in the list
friend = ["rohit","riya","aditya","nishant","aryan"]
print("add amit",friend.append('amit')) if "amit" not in friend else print('list',friend)
print(friend)

a = "rohit mandal"
print(a.title())
print(id(a))
a = ["r","o","s","i"]
print(len(a))

a = (1,"hey",3.4)
print(a)

print("rohit \n riya")

num=input("enter num(only 3 dig):")
total = int(num[0])+int(num[1])+int(num[2])
print(total)

name ="rohit"
print(name[5:0:-1])

num = int(input("enter:"))
print("even") if num%2 == 0 else  print("odd")

#python class 9
print("5 != 4:",5 != 4)
print("6 == 6:",6 == 6)
print("8 <= 10:",8 <= 10)
print("10 >= 9:",10 >= 9)
print("19 >=100:",19 >=100)
a = 11
b = 2
c = 10
print((a>b) and (a > c))
print((a<c)and (c<b))
print((a<c) or (c<b))
v=((a<c) or (c<b))
print(not v )
v =((a<c)and (c<b))
print(not v)
print(1 << 6)
a += 10
print(a)
a-=10
print(a)
a **= 12
print(a)
a /= 6
print(a)
print(a is b)
print(a is c)
print(a is not b)
print(a is not c)
a = ["amit","riya","rohit"]
b = 'rohit'
print(b in a)

import random as rd
a = [1,2,3,4,5]
num = (rd.randint(1,3))
print(rd.choice(a))
if num == 1:
  print("only 1 player can play")
elif num == 2:
  print("only 2 player can play")
else :
  print("only 3 player can play")    
for i in range(1,10):#n-1
  print('rohit')  
  print(i)
while True:
  print("rohit mandal")
  num = rd.randint(1,2)
  if num == 2

print("sit nagpur \n"*100)

a = int(input("enter a number1:"))
b = int(input("enter a number2:"))
c = int(input("enter a number3:"))
if a > b:
  print(a,"is greatest then",b)
if a > c:
  print(a,"is greatest then",c)
if b > a :
  print(b,"is greatest then",a)
if b > c:
  print(b ,"is greatest then",c)
if c > a:
  print(c,"is greatest then",a)
if c > b:
  print(c,"is greatest then",b)

import random
list1=["rock","paper","scissor"]
user = str(input("enter your choice [rock,paper,scissor]"))
computer = list1[random.randint(0,3)]
print("computer choice",computer)
if user  == computer:
  print("tie")
elif user == "rock":
     if computer == "paper":
       print("you win")
     else:
       print("you loose")
elif user == "paper":
     if computer == "scissor":
       print("you loose")
     else:
       print("you win")
elif user == "scissor":
     if computer =="paper":
       print("you win")
     else :
       print("you loose")
else:
    print("error")

import random
list1=["rock","paper","scissor"]
user = str(input("enter your choice [rock,paper,scissor]"))
computer = list1[random.randint(0,3)]
print("computer choice",computer)
if user  == computer:
  print("tie")
if user == "rock":
     if computer == "scissor":
       print("you win")
     if computer == "paper":
       print("you loose")
if user == "paper":
     if computer == "scissor":
       print("you loose")
     if computer == "rock":
       print("you win")
if user == "scissor":
     if computer =="paper":
       print("you win")
     if computer == "rock" :
       print("you loose")

num = float(input("enter you num:"))
if num%2 == 0:
  print("even")
if num%2 == 1:
  print("odd")  
num = float(input("enter you num:"))
if num > 0:
  print('postive')
if num < 0:
  print('negative') 
if num == 0:
  print(num)

#wap to get two number form input from user perform addition if the sec num is multiple of first other wise perform substracion
num1 = int(input("enter your number1:"))
num2 = int(input("enter your number2:"))

if num1%num2 == 0:
  print(num1+num2)
if num2%num1 != 0:
  print(num1*num2)

animal_list = ["cat","rat","tiger","python"]
if "lion" in animal_list:
  print("already there sir")
else:
  animal_list.append("lion")
  print("done sir")

print(animal_list)

#wap to find wether a number is even or odd using if else
num = float(input("enter number:"))
if num%2 == 0:
  print("even")
else:
  print('odd')

#wap to check weather a num enter by user is greater then 30 or equal to 30 greater then 30
num = int(input("enter a number:"))
if num <= 30:
  if num == 30 :
      print("num is equal to 30")
  else: 
      print("num is smaller then 30")    
else :
  print("num is greater then 30")

num = int(input("enter your num:"))
if num < 30:
    print("num is smaller then 30")  
elif num == 30 :
    print("num is equal to 30")  
else :
    print("num is greater then 30")

#wap to print grade of students base on the percentage sports if 90 up A+ if 80-90 A 70-80 b+ 70-60 b 60-50 c+ 40-50 c less then 40 fail
name = str(input("enter your name:"))
num = int(input("enter your marks:"))
if num > 90 and num <= 100 :
    print(f"cong {name} you got A+")
elif num >= 80 and num <= 90 :
    print(f"cong {name} you got A")
elif num >= 70 and num <= 79 :
    print(f"cong {name} you got B+")      
elif num >= 60 and num <= 69:
    print(f"cong {name} you got B")
elif num >= 50 and num <= 59:
    print(f"cong {name} you got c+")
elif num >= 40 and num <= 49:
    print(f"cong {name} you got c") 
elif num < 40 :
    print(f"sorry {name} you have failed")
else:
    print("invalid input")

for i in range(10):
   print(i)

num = int(input("enter you number"))
for i in range(1,11):
    print(f"{num}*{i} =",i*num)

for i in range(1,101):
  print("symbiosis institute of technology ,nagpur")

friend =["aditya","nishant","aryan","prathm","rohit"]
for i in friend:
     print(i,"number of character",len(i))

bear = {"grizzly":"angry","brown":"friendly","polar":"friendly"}
for bears in bear:
    if bear[bears] == "friendly":
      print("hello ",bears,"bear")
    else:
      print("bad bear")

#wap to print all prime num within a give range
num1 = int(input("enter your stop timeing:"))
num2 = int(input("enter your stop timeing:"))
a = 1
for i in range(num1,num2+1):
    if i == 2:
        print ("2 is prime number")
    elif i == 1:
        print ("1 is prime number")
    elif i == 3:
        print ("3 is prime number")
    elif i == 5:
        print("5 is prime number")
    elif i == 7:
        print("7 is prime number")            
    else:
        if i%2 == 0:
            a += 1
        elif i%3 == 0:
            a += 1
        elif i%5 == 0:
            a += 1    
        elif i%7 == 0:
            a += 1     
        else:
            print (i,"is prime number")
print ("none prime number =",a)

a = int(input("start:"))
b =int(input("stop:"))
for i in range(a,b+1):
  for j in range(2,i):
    if i%j==0:
      break
  else:
    print(i)

#odd even number

n =1
for i in range(5):
  print("* "*n)
  n +=1

n = int(input("user input"))
for i in range(n,0,-1):
  print("* "*n)
  n-=1

n = 1
m = 0
apl=["A","B","C","D"]
for i in range(4,0,-1):
  print(f"{apl[m]} "*n)
  m += 1
  n += 1

n = int(input("Enter the number of rows: "))  
m = (2 * n) - 2  
for i in range(0, n):  
    for j in range(0, m):  
        print(end=" ")  
    m = m - 1   
    for j in range(0, i + 1):   
        print( "* ", end=' ')  
    print(" ")

n = int(input("Enter the number of rows: "))  
apl =["a","b","c","d"]
m = (2 * n) - 2  
for i in range(0, n):  
    for j in range(0, m):  
        print(end=" ")  
    m = m - 1   
    for j in range(0, i + 1):   
        print("*", end=' ')  
    print(" ")

#while luop
#wap to find sum of digits of a number given by user
num = int(input())
sum =0
while (num > 0):
    digit = num % 10
    sum += digit
    num = num//10 
print(sum)

num = str(input())
sum =0
for i in num:
  sum += int(i)
print(sum)

n = int(input())
numB,z =n,0
count =0
while (n != 0):
  count +=1
  n = n//10
  z += 1
sum1,k= 0,numB
while (numB != 0):
  sum1 += pow(numB%10,count)
  numB = numB//10
if sum1==k:
  print("arm")
else:
  print("not arm")

p = int(input())
z = 0
while (p > 0):
    p = p//10
    z +=1 # z +=1
print(z)

for i in range(1,100):
  print("hello wrold")
  if i == 20:
    pass
  elif i ==50:
    print("go")
    continue
    print("do not go")
  elif i == 99:
    break
  else:
    print(i)

#home work
ranges = int(input())
for i in range(ranges):
    n = int(input())
    numB,z =n,0
    count =0
    while (n != 0):
      count +=1
      n = n//10
      z += 1
    sum1,k= 0,numB
    while (numB != 0):
      sum1 += pow(numB%10,count)
      numB = numB//10
    if sum1==k:
      print("arm")
    else:
      print("not arm")

num_start = int(input())
num_stop =int(input())
sum = num_start
n1,n2 =num_start,num_start+1
print("==============x===========")
for i in range(num_start,num_stop):
    print(sum )
    n1=n2
    n2=sum
    sum = n1+n2

def add(x,y):
  '''add function'''
  return x + y

def power(x):
  #power function
  return x**2 , x**3

def aryan():
   for i in range(1,10):
     print()   
def sumofdigit(num):
  sum =0
  while (num!=0):
    sum = sum + num%10
    num = num//10
  print(sum)  
if __name__=="__main__":
  num = int(input("enter num:"))
  sumofdigit(num)

def grade(name,num):
  if num > 90 and num <= 100 :
     print(f"cong {name} you got A+")
  elif num >= 80 and num <= 90 :
      print(f"cong {name} you got A")
  elif num >= 70 and num <= 79 :
     print(f"cong {name} you got B+")      
  elif num >= 60 and num <= 69:
      print(f"cong {name} you got B")
  elif num >= 50 and num <= 59:
      print(f"cong {name} you got c+")
  elif num >= 40 and num <= 49:
      print(f"cong {name} you got c") 
  elif num < 40 :
      print(f"sorry {name} you have failed")
  else:
     print("invalid input")    
if __name__=="__main__":
  num = int(input("enter your marks:"))
  name = str(input("enter your name:"))
  grade(name,num)

help(add)
add.__doc__

def fibb(stop):
   num_start = 0
   num_stop = stop
   sum = num_start
   n1,n2 =num_start,num_start+1
   for i in range(num_start,num_stop):
       print(sum )
       n1=n2
       n2=sum
       sum = n1+n2

if __name__=="__main__":
    stop = int(input("enter range:"))
    fibb(stop)

def fibb(stop):
   num= stop
   sum = 0
   n1,n2 =0,1
   while num > sum: 
       print(sum )
       n1=n2
       n2=sum
       sum = n1+n2

if __name__=="__main__":
    stop = int(input("enter range:"))
    fibb(stop)

def fibbo(n):
  a,b =0,1
  while a < n:
    print(a,end=" ")
    a,b =b,a+b
fibbo(10)

def f():
  y = 5
  print(f'inside function y is :{y} & id :{id(y)} ')
  x = 5
  print(f'inside function y is :{x} & id :{id(x)} ')
f()  
y

def f(x):
  x = ["nagpur","pune","mumbai","nasik"]
city_list = ["nagpur","pune","mumbai","nasik"]
print(f"pro outside function city_list is:{city_list} and is:{id(city_list)}")
f(city_list)
print(f"outside function city_list is :{city_list} and id:{id(city_list)}")

# wap to reverse 
def rev(n):
  x =0
  while n!=0:
    x =x*10+n%10
    n = n//10
  print(x) 

#wap to create a function that insert an element of list at aparticular position
x = []
def  ins():
   x.insert(0,1)
   x.insert(5,5)
   x.insert(2,3)
   print(x) 
x = [29,36,63,255,990]
print(x)
print("update")
u = [1,2,3,34,57,45,646,8293]
def new():
    print(u)
    user = "y"
    while user != "n":
      a= int(input("enter position:"))
      b=int(input("enter element:"))
      u.insert(a-1,b) 
      user = str(input("do you want to continue(y,n):"))
    print(u)
      
 #if we use default argument it will follow by non defult argument
def p(x=1,y=1,z=1):
    return ( x ** y **z)
print(p(1))
print(p(11,3))
print(p(2,2,3))

i=5
print(f'The argument outside before function is {i}')
def f(arg=i):
  print(f'The argument is {arg} & {id(arg)}')

  i=6
  f(6)
  f()
  print(f'The argument outside after function is {i} & {id(i)}')
def f(a = 1,l=[]):
  l.append(a)
  print(id(l),end=":")
  print( l, end="\n" ) 
f()
f(2)
f(3)

#Write a program using functions. Find function x & do not take any parameter as inout but creates a list of 5 friends. The function checks if the friend is present in the list or not.
#It does nothing otherwise append the friend name in the list. 
def x():
  l = ["rohit","nishant","aditya","aryan","shreya"]
  for i in l:
    if i == "riya":
      continue
    else:
      break
  l.append("riya")      
  print(l)
x()

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
no_punct = ""
my_str = str(input("enter string value:"))
for i in my_str:
   if i not in punctuations:
       no_punct = no_punct + i
print(no_punct)

def student(name ,classs= "12",roll= "23"):
    print("your name is ",name)
    print("class :",classs)
    print("roll:",roll)
student(name = "shreya rohit mandal ",roll = "29", classs="11")

#9/12/22
x = lambda a:a+10
print(x(5))
y = lambda b:b+12
print(y(7))

list_number = [2,3,4,5,6,7]
odd_count = list(filter(lambda x: (x%2 != 0) , list_number))
even_count = list(filter(lambda x: (x%2 == 0) , list_number))
print("Even numbers: ", even_count)
print("Odd numbers : ", odd_count)

m  = (lambda x:
      (x % 2 and "odd" or "ever"))(3)
print(m)

print((lambda x,y,z: x+y+z)(1,2,3))
print((lambda x,y,z = 3:x+y+z)(1,2))
print((lambda x,y,z=3:x+y+z)(1,y=2))
print((lambda *args: sum(args))(1,2,3))
print((lambda **kwargs: sum(kwargs.values()))(one=1,two=2,three=3))
print((lambda x,*,y=0,z =0:x+y+z)(1,y=2,z=3))

#write a program to 5 number as a input at oncce to print factorial of each number using map function 
def fac():
     a =  list(map(int,input().split()))
     n = 0
     product = 1
     for j in a:
         for i in range(a[n],0,-1):
             product *=i 
         print("factorial of ",a[n],"=",product)    
         n += 1
fac()

import math
def fac():
  a = list(map(int,input().split()))
  pst = list(map(math.factorial,a))
  print(pst)
if __name__=="__main__":
  fac()

dir(math)

help(math)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile cal.py
# def add(x,y):
#    '''this function is use to add two number '''
#     return x+y
# def sub(x,y):
#     '''this function is use to sub two number '''
#     return x-y
# def mul(x,y):
#     '''this function is use to mul two number '''
#     return x*y
# def div(x,y):
#     '''this function is use to div two number '''
#     return x/y        
# if __name__=="__main__":
#   '''this is a cal function
#       you can perform 
#       add() -- addition
#       sub()  --substracion
#       mul() --multplication
#       div() --division '''

import cal
print(cal.add(1,2))

import cal
help(cal)

''' create a python module all the function create by you'''

#PYTHON CLASS

"""The __init__() Function
The examples above are classes and objects in their simplest form, and are not really useful in real life applications.

To understand the meaning of classes we have to understand the built-in __init__() function.

All classes have a function called __init__(), which is always executed when the class is being initiated.

Use the __init__() function to assign values to object properties, or other operations that are necessary to do when the object is
"""

class students:
    college= "sit"
    def __init__(self):
      self.sem = "I"
      self.strength = 66
      self.section = "c"
    def Branch(self):
      print("This is CSE"+self.sem+"semester")
  
rohit = students()
rohit.section

"""The __str__() Function
The __str__() function controls what should be returned when the class object is represented as a string.

If the __str__() function is not set, the string representation of the object is returned:
"""

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1)

"""INHERITANCE:
it is a feature or a process in which ,new classes are created form the existing classes.
"""

class student:
    domain = "btech"
    def display(self):
      print("the domain is:",self.domain)
students = student()

students.display()

class siustudent:
  domain = "btech"
  def __init__(self,section=c,prn):
    self.section = section
    self.prn = prn
  def display(self):
    print("the department :",self.domain)
    print("your section is :",self.section)
    print("your prn is :",self.prn)  
rohit = siustudent("c",22070521075)
rohit.display()

class siustudents(siustudent):
    qualification = "btech"
    def __init__(self,class_number):
      self.branch = "cse"
      self.class_number  = class_number
    def diplay(self):
      print("the qualification :",self.qualification)
      print("branch is :",self.branch)
      print("class room",self.room_number)
student =siustudents(103)

student.display()

"""recursion:
function call itself
"""

def fun(n):
  if n == 1:
    return 1
  else:
    return 2+fun(n-1) 
if __name__=="__main__":
    print(fun(4))

def fact(n):
  if n == 1:
    return 1
  else:
    return n*fact(n-1)
fact(5)

#write a program to find sum of digit of user given number using recursion
def sumofdigit(n):
   if n == 0:
      return 0
   else:
      return n%10 + sumofdigit(n//10)    

sumofdigit(192012903710237014790)

def sumofdigit(n):
  print(0) if n == 0 else print(n%10 + sumofdigit(n//10))   
sumofdigit(10)

#wap to create a class animal number of eyes ,leg , tail,and bhaivour ..subclass bird to over write the categare

class animal:
     def __init__(self,neye,nleg,ntail,behaviour):

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fibo.py
# 
# def fibb(n):
#    a,b =0,1  
#    while a < n:
#       print(a,end=" ")
#       a,b =b,a+b
# if __name__=="__main__":
#     stop = int(input("enter range:"))
#     fibb(stop)

import fibo
fibo.fibb(10)
